name: Network CI/CD Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  validate:
    name: Validate Configuration Change
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: pip install pyyaml jinja2

      - name: Run Validation Script
        # No 'working-directory' is needed here.
        # The runner is already in the root of your project.
        run: python scripts/validate_change.py

  deploy:
    name: Deploy to Device
    needs: validate
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Python and Dependencies
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - run: pip install pyyaml jinja2 ncclient netmiko

      - name: Deploy to NETCONF Device
        run: python scripts/master_deploy.py router1-netconf

      - name: Deploy to Legacy CLI Device
        run: python scripts/master_deploy.py switch1-legacy

  drift-detect:
    name: Detect Configuration Drift
    if: github.event_name == 'schedule'
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Python and Dependencies
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - run: pip install pyyaml jinja2 ncclient netmiko

      - name: Check Drift on NETCONF Device
        run: python scripts/check_drift.py router1-netconf

      - name: Check Drift on Legacy CLI Device
        run: python scripts/check_drift.py switch1-legacy